name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.1]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Code Linting
        run: pnpm types:check && eslint --ext .ts,.tsx,.js,.jsx --max-warnings 0 . && prettier . --check --plugin=prettier-plugin-astro

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
